# Netlify deployment configuration

[build]
  command = "sh build.sh" # Script to build all React components
  publish = "dist"                     # The Netlify deploy directory
[build.environment]
  NODE_VERSION = "18"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security and Permissions Headers
[[headers]]
  for = "/*" # Apply to all pages
  [headers.values]
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), magnetometer=(), gyroscope=(), payment=(), interest-cohort=()"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    # Add other security headers here if needed in the future
