// Environment Configuration: development
// Generated by configure-env.sh on May 17, 2025

const envConfig = {
    environment: 'development',
    baseUrl: '/',
    authConfig: {
        tier: 0, // 0: Simple prompt, 1: Login page with hash
        password: 'complexdemo',
        sessionKey: 'tier0Password'
    },
    // Add other configuration values here...
};

// Make config globally accessible
window.envConfig = envConfig;

export default envConfig;
