name: Refresh Airtable Index Data

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  refresh-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to commit changes back to the repo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Secrets from Bitwarden
        uses: bitwarden/sm-action@v2
        with:
          access_token: ${{ secrets.BWS_ACCESS_TOKEN }} # Ensure this GitHub secret is set
          secrets: |
            c2866edf-1e4d-441c-87a3-b21b010c3001 > AIRTABLE_API_KEY

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use a recent Python 3 version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f integrations/airtable/requirements.txt ]; then
            pip install -r integrations/airtable/requirements.txt
          else
            echo "requirements.txt not found, skipping pip install."
          fi

      - name: Run Airtable script
        run: |
          python integrations/airtable/airtable_workflow_extractor.py
          # Command-line arguments for base-id and table-id are removed
          # as the script now reads them from airtable_config.json.
          # Ensure airtable_config.json has a task that outputs to data/airtable_index_data.json
          # for the commit step below to work as intended.

      - name: Commit and push if data changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/airtable_index_data.json
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Automated update of Airtable index data"
            git push
          fi
